=== totalcms/cms/schemas/meta.json
{
    "$schema"     : "https://json-schema.org/draft/2020-12/schema",
    "$id"         : "https://www.totalcms.co/schemas/meta.json",
    "id"          : "meta",
    "type"        : "object",
    "description" : "A schema for a Total CMS Collection meta data file.",
    "properties"  : {
        "id": {
            "$ref": "https://www.totalcms.co/schemas/properties/slug.json",
            "description": "The id of the collection."
        },
        "name": {
            "type"  : "string",
            "description": "The name of the collection."
        },
        "description": {
            "type"  : "string",
            "description": "The description of the collection."
        },
        "schema": {
            "$ref": "https://www.totalcms.co/schemas/properties/slug.json",
            "description": "The name of the schema that the collection objects conform to"
        },
        "url": {
            "$ref": "https://www.totalcms.co/schemas/properties/url.json"
        },
		"properties": {
			"$ref": "https://www.totalcms.co/schemas/properties.json"
		},
		"customProperties": {
			"type": "object",
			"description": "Custom values for the form fields for specific objects.",
			"patternProperties": {
				"^\\S+$": {
					"$ref": "https://www.totalcms.co/schemas/properties.json"
				}
			}
		}
    },
    "required": [
        "id",
        "name",
        "schema",
		"properties"
    ]
}

=== totalcms/cms/tests/test-data/new-text-collection.json
{
    "id": "text",
    "schema": "text",
    "name": "Custom Text Collection",
    "description": "A collection to test",
    "url": "",
    "properties": {
        "id": {
            "label": "Text ID",
            "help": "A unique ID for this text. No spaces or special characters.",
            "field": "id"
        },
        "text": {
            "label": "Text",
            "help": "Edit the text here.",
            "field": "textarea"
        }
    }
}
